services:
  - type: web
    name: mansourai-bot
    env: python
    plan: free
    rootDir: src
    buildCommand: "pip install -r ../requirements.txt"
    startCommand: "python main.py"
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: WEBHOOK_URL
        sync: false
